baseURL = "https://pokernabrasil.com"
languageCode = "pt-BR"
title = "pokernabrasil"
enableRobotsTXT = true
defaultContentLanguage = "pt-BR"
[languages]
  [languages.pt-br]
  languageName = "Português (Brasil)"
  weight = 1
  contentDir = "content"

[params]
  description = "Это минималистичный сайт, созданный на Hugo для SEO."
  logo = "images/logo.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
frontmatterFormat = "yaml"
[module]
  disable = true
